apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-processing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-processing
  template:
    metadata:
      labels:
        app: location-processing
    spec:
      containers:
        - image: rsoproject.azurecr.io/location-processing:latest
          name: location-processing
          ports:
            - containerPort: 8083
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: location-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: location-processing