kumuluzee:
  name: location-processing
  env:
    name: dev
  version: 1.0.0
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  server:
#    base-url: http://localhost:8083
    base-url: http://52.191.32.66
#    base-url: http://location-processing:8083
    http:
      port: 8083
  discovery:
    etcd:
      hosts: http://localhost:2379
  openapi:
    enabled: true
  datasources:
#    - jndi-name: jdbc/EventCatalogDS
#      connection-url: jdbc:postgresql://localhost:5432/event-catalog
#      username: postgres
#      password: postgres
    - jndi-name: jdbc/EventCatalogDS
      connection-url: jdbc:postgresql:///rsodatabase?cloudSqlInstance=a1-projekat:us-central1:rsodatabase&socketFactory=com.google.cloud.sql.postgres.SocketFactory
      username: postgres1
      password: postgres
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                        <Configuration name="comments">
                            <Appenders>
                                <Console name="console" target="SYSTEM_OUT">
                                    <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                </Console>
                                <Socket name="logstash" host="852bac38-fc96-4293-8c3c-78c39d020464-ls.logit.io"
                                port="29177" protocol="udp">
                                    <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                </Socket>
                            </Appenders>
                            <Loggers>
                                <!-- Default logger -->
                                <Root level="all">
                                    <AppenderRef ref="console" level="info" />
                                    <AppenderRef ref="logstash" level="trace" />
                                </Root>
                            </Loggers>
                        </Configuration>'

  persistence-units:
    - name: "event-catalog-jpa"
      continue-on-error: false
geo-properties:
  geocode-key:

# GEOPROPERTIES_GEOCODEKEY