kumuluzee:
  name: location-processing
  env:
    name: dev
  version: 1.0.0
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/EventCatalogDS
      connection-url: jdbc:postgresql://localhost:5432/event-catalog
      username: postgres
      password: postgres
  persistence-units:
    - name: "event-catalog-jpa"
      continue-on-error: false
geo-properties:
  geocode-key: "AIzaSyAvSGseJIVEoPaF22P8ebFINbKn70IVBxo"
